# Generated by Django 2.1 on 2018-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('launch_date',)},
        ),
    ]
