# Generated by Django 2.1 on 2018-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180819_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='launch_date',
            field=models.DateTimeField(),
        ),
    ]
